my_nations:
    #- Latvia
    #- Lithuania
    - Nordic Federation
    #- Finland
    - Southern Africa Federation
    #- Eswatini
    #- Namibia
    #- Botswana
    #- Zimbabwe
    #- Mozambique
    #- Angola
    - East African Federation
    - China
    - South Korea
    #- Austria
    - Venezuela
    #- France
    #- United Kingdom
    - European Union

    #- Zambia
    #- Malawi
    #- Madagascar
    #- South Sudan
    #- Sudan
    #- Chad
    #- Central African Republic
    #- Republic of the Congo
    #- Niger
    #- Togo
    #- Ghana
    #- Benin
    #- Liberia
    #- Sierra Leone
    #- Mauritania
    #- Mali
    ##- Morocco
    ##- Tunisia
    ##- Ethiopia

    #- Algeria
    #- Djibouti
    #- Eritrea

    #- Guinea-Bissau
    #{
    #    "value": 18184
    #},
    #{
    #    "value": 84690
    #},
    #{
    #    "value": 85100
    #},
    #{
    #    "value": 105007
    #},
    #{
    #    "value": 105029
    #}
    #
    #"value": 60762
