my_nations:
  - Latvia
  - Lithuania
  - Denmark
  - Sweden
  - Finland
  - Estonia
  - South Africa
  - Eswatini
  - Namibia
  - Botswana
  - Zimbabwe
  - Mozambique
  - Angola
  - Congo
  - Zambia
  - Madagascar
  - Uganda
  - Tanzania
  - Rwanda-Burundi
  - Kenya
  - Somalia
  - South Sudan
