my_nations:
  - Latvia
  - Lithuania
  - Denmark
  - Sweden
  - Finland
  - Estonia
  - South Africa
  - Eswatini
  - Namibia
  - Botswana
  - Lesotho
  - Zimbabwe
  - Mozambique
  - Angola
  - Congo
  - Zambia
  - Madagascar
