my_nations:
    #- Latvia
    #- Lithuania
    - Nordic Federation
    #- Finland
    - Southern Africa Federation
    #- Eswatini
    #- Namibia
    #- Botswana
    #- Zimbabwe
    #- Mozambique
    #- Angola
    - East African Federation
    - China
    - South Korea
    #- Austria
    #- Venezuela
    #- France
    #- United Kingdom
    - European Union

    #- Zambia
    #- Malawi
    #- Madagascar
    #- South Sudan
    #- Sudan
    #- Chad
    #- Central African Republic
    #- Republic of the Congo
    #- Niger
    #- Togo
    #- Ghana
    #- Benin
    #- Liberia
    #- Sierra Leone
    #- Mauritania
    #- Mali
    ##- Morocco
    ##- Tunisia
    ##- Ethiopia

    #- Algeria
    #- Djibouti
    #- Eritrea

    #- Guinea-Bissau
    #{
    #    "value": 18184
    #},
    #{
    #    "value": 84690
    #},
    #{
    #    "value": 85100
    #},
    #{
    #    "value": 105007
    #},
    #{
    #    "value": 105029
    #}
    ##
    #"value": 60762#
#
#    {
#        "value": 1403
#    }
#
#    {
#        "value": 3446
#    },
#    {
#        "value": 3455
#    },
#    {
#        "value": 3437
#    },
#    {
#        "value": 3464
#    },
#    {
#        "value": 3473
#    },
#    {
#        "value": 3482
#    }
#"breakawayParent": {
#    "value": 3734
#},
#"allies": [
#    {
#        "value": 4143
#    }
#],
#
#"breakawayParent": null,   // 429615
#
#
#"breakawayParent": {
#    "value": 3734
#},

# Gabon
# South Korea
# Liangguang
# China
# West Africa Community
# united kingdom
# equatorial

#                    "federation": {
#                        "value": 63213
#                    },
# 4242
