my_nations:
  - Latvia
  - Lithuania
  - Nordic Federation
  #- Finland
  - Southern Africa Federation
  #- Eswatini
  #- Namibia
  #- Botswana
  #- Zimbabwe
  #- Mozambique
  #- Angola
  - East African Federation
  #- Zambia
  #- Malawi
  #- Madagascar
  #- South Sudan
  #- Sudan
  #- Chad
  #- Central African Republic
  #- Republic of the Congo
  #- Niger
  #- Togo
  #- Ghana
  #- Benin
  #- Liberia
  #- Sierra Leone
  #- Mauritania
  #- Mali
