my_nations:
  - Belarus
  - Belgium-Luxembourg
  - Cambodia
  - East African Federation
  - Kazakhstan
  - Latvia
  - Lithuania
  - Madagascar
  - Nordic Federation
  - United Kingdom
  - Southern Africa Federation
  - South American Union
  - Mauritius
  - Germany
  - Central African Republic
  - Republic of the Congo
  - Cameroon
  - Benin
  - Togo
  - Ghana
  - Ivory Coast
  - Burkina Faso
  - North Korea
